# Generated by Django 5.1.2 on 2024-10-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estilo',
            field=models.CharField(blank=True, choices=[('Aventura', 'Aventura'), ('Relaxante', 'Relaxante'), ('Cultural', 'Cultural'), ('Família', 'Família'), ('Luxuoso', 'Luxuoso')], max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='gastronomia',
            field=models.CharField(blank=True, choices=[('Culinária Oriental', 'Culinária Oriental'), ('Vegetariano', 'Vegetariano'), ('Churrasco', 'Churrasco'), ('Vegano', 'Vegano'), ('Frutos do Mar', 'Frutos do Mar')], max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesses',
            field=models.CharField(blank=True, choices=[('Praia', 'Praia'), ('Cachoeira', 'Cachoeira'), ('Natureza', 'Natureza'), ('Cultura Local', 'Cultura Local'), ('Trilha', 'Trilha'), ('Passeios em Família', 'Passeios em Família')], max_length=50),
        ),
    ]
