# Generated by Django 5.1.2 on 2024-11-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_pontoturistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estilo',
            field=models.CharField(blank=True, choices=[('Relaxante', 'Relaxante'), ('Cultural', 'Cultural'), ('Família', 'Família'), ('Luxuoso', 'Luxuoso'), ('Gastronômico', 'Gastronômico')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='interesses',
            field=models.CharField(blank=True, choices=[('Praia', 'Praia'), ('Natureza', 'Natureza'), ('Cultura Local', 'Cultura Local'), ('Aventura', 'Aventura'), ('Compras', 'Compras')], max_length=50),
        ),
    ]
