# Generated by Django 5.1.2 on 2024-10-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_pontos_turisticos/')),
                ('interesse_praia', models.BooleanField(default=False)),
                ('interesse_natureza', models.BooleanField(default=False)),
                ('interesse_cultura_local', models.BooleanField(default=False)),
                ('interesse_aventura', models.BooleanField(default=False)),
                ('interesse_compras', models.BooleanField(default=False)),
                ('culinaria_oriental', models.BooleanField(default=False)),
                ('vegetariano', models.BooleanField(default=False)),
                ('churrasco', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('frutos_do_mar', models.BooleanField(default=False)),
                ('estilo_relaxante', models.BooleanField(default=False)),
                ('estilo_cultural', models.BooleanField(default=False)),
                ('estilo_familia', models.BooleanField(default=False)),
                ('estilo_luxuoso', models.BooleanField(default=False)),
                ('estilo_gastronomico', models.BooleanField(default=False)),
                ('popularidade', models.IntegerField(help_text='Popularidade de 1 a 10')),
            ],
        ),
    ]
